PACKAGECONFIG:append:k3 = " no-idle-timeout"
PACKAGECONFIG:append:upstream:colibri-imx6ull = " use-pixman"
PACKAGECONFIG:append:upstream:colibri-imx6ull-emmc = " use-pixman"
PACKAGECONFIG:append:upstream:colibri-imx7 = " use-pixman"
PACKAGECONFIG:append:upstream:colibri-imx7-emmc = " use-pixman"
